# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.study.title: 'symfony-ecosystem-study'
    app.study.day: 7

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # interface → implementace (jako bind v Laravel AppServiceProvider)
    App\Contract\GreetingGeneratorInterface: '@App\Service\FormalGreetingGenerator'

    App\Service\FormalGreetingGenerator:
        tags: ['app.greeting_generator']

    App\Service\CasualGreetingGenerator:
        tags: ['app.greeting_generator']

    App\Service\StudyInfoProvider:
        arguments:
            $studyTitle: '%app.study.title%'
            $studyDay: '%app.study.day%'
            $appEnv: '%kernel.environment%'

    App\Controller\CqrsDemoController:
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@query.bus'

    App\MessageHandler\Command\CreateStudyTopicHandler:
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
