parameters:
    app.study.title: 'symfony-ecosystem-study'
    app.study.day: 15

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Contract\GreetingGeneratorInterface: '@App\Service\FormalGreetingGenerator'

    App\Service\FormalGreetingGenerator:
        tags: ['app.greeting_generator']

    App\Service\CasualGreetingGenerator:
        tags: ['app.greeting_generator']

    App\Service\StudyInfoProvider:
        arguments:
            $studyTitle: '%app.study.title%'
            $studyDay: '%app.study.day%'
            $appEnv: '%kernel.environment%'

    App\Messenger\Transport\AmqpSimTransportFactory:
        tags: ['messenger.transport_factory']

    App\Messenger\Transport\AmqpLibTransportFactory:
        tags: ['messenger.transport_factory']

    App\Controller\CqrsDemoController:
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@query.bus'

    App\Controller\PulseController:
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@query.bus'

    App\MessageHandler\Command\CreateStudyTopicHandler:
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'

    App\MessageHandler\Command\CreateWorkOrderHandler:
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'

    App\MessageHandler\Event\AdvanceWorkOrderHandler:
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
